# Generated by Django 5.0.6 on 2024-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Проверочное слово'),
        ),
    ]
